name: Node.js push on feature branch

on:
  push:
    branches: [feature/*]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: node:12.16.2
    steps:
      - uses: actions/checkout@v2

      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.GPG_PASSPHRASE }} --output ./src/config.json --decrypt ./src/config.json.gpg
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build 
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true