name: Node.js push on feature branch

on:
  push:
    branches: [feature/*]

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-18.04
    container:
      image: node:12.22.12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.GPG_PASSPHRASE }} --output ./src/config.json --decrypt ./src/config.develop.json.gpg
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build --if-present
        env:
          CI: false
          
      - name: Test
        run: npm test
        env:
          CI: false
